"""Create initial database schema from models

Revision ID: a39a692e2f02
Revises: 
Create Date: 2025-08-25 01:31:08.059750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a39a692e2f02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='organizationstatus'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('data_region', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plan_type', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='plantype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('api_requests_limit', sa.Integer(), nullable=False),
    sa.Column('websites_limit', sa.Integer(), nullable=False),
    sa.Column('team_members_limit', sa.Integer(), nullable=False),
    sa.Column('data_storage_gb_limit', sa.Integer(), nullable=False),
    sa.Column('crawl_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_last_changed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('subscription_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('google_access_token', sa.Text(), nullable=True),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('google_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_scopes', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_via', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_table('activity_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('user_activities', sa.Integer(), nullable=True),
    sa.Column('site_activities', sa.Integer(), nullable=True),
    sa.Column('performance_activities', sa.Integer(), nullable=True),
    sa.Column('seo_activities', sa.Integer(), nullable=True),
    sa.Column('content_activities', sa.Integer(), nullable=True),
    sa.Column('team_activities', sa.Integer(), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=True),
    sa.Column('pages_analyzed', sa.Integer(), nullable=True),
    sa.Column('keywords_tracked', sa.Integer(), nullable=True),
    sa.Column('alerts_triggered', sa.Integer(), nullable=True),
    sa.Column('avg_lcp', sa.Float(), nullable=True),
    sa.Column('avg_fid', sa.Float(), nullable=True),
    sa.Column('avg_cls', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summary_org_date', 'activity_summaries', ['organization_id', 'date'], unique=True)
    op.create_index(op.f('ix_activity_summaries_id'), 'activity_summaries', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_preview', sa.String(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action_timestamp', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('idx_audit_logs_resource_type_resource_id', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_user_id_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('captured_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captured_knowledge_id'), 'captured_knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_captured_knowledge_knowledge_id'), 'captured_knowledge', ['knowledge_id'], unique=True)
    op.create_table('competitive_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intelligence_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intelligence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitive_intelligence_id'), 'competitive_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_competitive_intelligence_intelligence_id'), 'competitive_intelligence', ['intelligence_id'], unique=True)
    op.create_table('competitor_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authority', sa.Integer(), nullable=True),
    sa.Column('backlinks', sa.Integer(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.Integer(), nullable=True),
    sa.Column('positions', sa.JSON(), nullable=True),
    sa.Column('avg_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_tracking_domain'), 'competitor_tracking', ['domain'], unique=False)
    op.create_index(op.f('ix_competitor_tracking_user_id'), 'competitor_tracking', ['user_id'], unique=False)
    op.create_table('content_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_briefs_brief_id'), 'content_briefs', ['brief_id'], unique=True)
    op.create_index(op.f('ix_content_briefs_id'), 'content_briefs', ['id'], unique=False)
    op.create_table('content_enhancements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enhancement_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enhancement_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_enhancements_enhancement_id'), 'content_enhancements', ['enhancement_id'], unique=True)
    op.create_index(op.f('ix_content_enhancements_id'), 'content_enhancements', ['id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=255), nullable=True),
    sa.Column('full_domain', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('verification_value', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('in_search_console', sa.Boolean(), nullable=False),
    sa.Column('in_analytics', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index(op.f('ix_domains_domain'), 'domains', ['domain'], unique=False)
    op.create_index(op.f('ix_domains_full_domain'), 'domains', ['full_domain'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('channels', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_table('organization_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_audit_logs_action'), 'organization_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_organization_audit_logs_created_at'), 'organization_audit_logs', ['created_at'], unique=False)
    op.create_table('organization_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssl_cert_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_domains_created_at'), 'organization_domains', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_domains_domain'), 'organization_domains', ['domain'], unique=True)
    op.create_table('organization_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'ANALYST', 'VIEWER', name='memberrole'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_created_at'), 'organization_invitations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_token'), 'organization_invitations', ['token'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'ANALYST', 'VIEWER', name='memberrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SUSPENDED', 'INACTIVE', name='memberstatus'), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('dashboard_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='unique_org_user')
    )
    op.create_index(op.f('ix_organization_members_created_at'), 'organization_members', ['created_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('personalized_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalized_recommendations_id'), 'personalized_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_personalized_recommendations_recommendation_id'), 'personalized_recommendations', ['recommendation_id'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_scenario_id'), 'scenarios', ['scenario_id'], unique=True)
    op.create_table('serp_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('device', sa.String(length=50), nullable=False),
    sa.Column('organic_results', sa.JSON(), nullable=True),
    sa.Column('serp_features', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('organic_count', sa.Integer(), nullable=False),
    sa.Column('paid_count', sa.Integer(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('competition_level', sa.String(length=50), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_analyses_query'), 'serp_analyses', ['query'], unique=False)
    op.create_index(op.f('ix_serp_analyses_user_id'), 'serp_analyses', ['user_id'], unique=False)
    op.create_table('serp_feature_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_type', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ctr_impact', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_feature_tracking_feature_name'), 'serp_feature_tracking', ['feature_name'], unique=False)
    op.create_index(op.f('ix_serp_feature_tracking_query'), 'serp_feature_tracking', ['query'], unique=False)
    op.create_index(op.f('ix_serp_feature_tracking_user_id'), 'serp_feature_tracking', ['user_id'], unique=False)
    op.create_table('sge_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('target_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('optimization_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_sge_readiness', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sge_analyses_analysis_id'), 'sge_analyses', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_sge_analyses_id'), 'sge_analyses', ['id'], unique=False)
    op.create_table('sge_monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monitor_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sge_monitors_id'), 'sge_monitors', ['id'], unique=False)
    op.create_index(op.f('ix_sge_monitors_monitor_id'), 'sge_monitors', ['monitor_id'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('crawl_schedule', sa.String(length=255), nullable=True),
    sa.Column('max_urls_per_crawl', sa.Integer(), nullable=False),
    sa.Column('respect_robots_txt', sa.Boolean(), nullable=False),
    sa.Column('crawl_javascript', sa.Boolean(), nullable=False),
    sa.Column('last_crawled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategic_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('strategy_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('execution_period', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_ledger_id'), 'strategic_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_strategic_ledger_strategy_id'), 'strategic_ledger', ['strategy_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PAST_DUE', 'CANCELED', 'TRIALING', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'ANNUAL', name='billingcycle'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_email'), 'team_members', ['email'], unique=True)
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_table('threat_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('threat_type', sa.String(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_scenarios_id'), 'threat_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_threat_scenarios_threat_id'), 'threat_scenarios', ['threat_id'], unique=True)
    op.create_table('tuning_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuning_insights_id'), 'tuning_insights', ['id'], unique=False)
    op.create_index(op.f('ix_tuning_insights_insight_id'), 'tuning_insights', ['insight_id'], unique=True)
    op.create_table('usage_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_requests', sa.Integer(), nullable=False),
    sa.Column('api_requests_limit', sa.Integer(), nullable=False),
    sa.Column('data_storage_gb', sa.Float(), nullable=False),
    sa.Column('data_storage_limit_gb', sa.Float(), nullable=False),
    sa.Column('team_members', sa.Integer(), nullable=False),
    sa.Column('team_members_limit', sa.Integer(), nullable=False),
    sa.Column('websites_monitored', sa.Integer(), nullable=False),
    sa.Column('websites_limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_statistics_id'), 'usage_statistics', ['id'], unique=False)
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_performance_alerts', sa.Boolean(), nullable=False),
    sa.Column('email_security_alerts', sa.Boolean(), nullable=False),
    sa.Column('email_billing_alerts', sa.Boolean(), nullable=False),
    sa.Column('email_team_updates', sa.Boolean(), nullable=False),
    sa.Column('email_weekly_digest', sa.Boolean(), nullable=False),
    sa.Column('app_enabled', sa.Boolean(), nullable=False),
    sa.Column('app_performance_alerts', sa.Boolean(), nullable=False),
    sa.Column('app_security_alerts', sa.Boolean(), nullable=False),
    sa.Column('app_billing_alerts', sa.Boolean(), nullable=False),
    sa.Column('app_team_updates', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_performance_alerts', sa.Boolean(), nullable=False),
    sa.Column('push_security_alerts', sa.Boolean(), nullable=False),
    sa.Column('push_billing_alerts', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_timezone', sa.String(length=50), nullable=False),
    sa.Column('max_emails_per_day', sa.Integer(), nullable=False),
    sa.Column('max_notifications_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_notification_preferences_id'), 'user_notification_preferences', ['id'], unique=False)
    op.create_table('background_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.Enum('CRAWL', 'WEBSITE_CRAWL', 'CORE_WEB_VITALS', 'CORE_WEB_VITALS_ANALYSIS', 'SEO_ANALYSIS', 'LOG_ANALYSIS', 'PERFORMANCE_CHECK', 'REPORT_GENERATION', 'REVENUE_ANALYSIS', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index('idx_task_celery', 'background_tasks', ['celery_task_id'], unique=False)
    op.create_index('idx_task_site_type', 'background_tasks', ['site_id', 'task_type'], unique=False)
    op.create_index('idx_task_status_type', 'background_tasks', ['status', 'task_type'], unique=False)
    op.create_index('idx_task_user_created', 'background_tasks', ['user_id', 'created_at'], unique=False)
    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_index(op.f('ix_billing_events_event_type'), 'billing_events', ['event_type'], unique=False)
    op.create_table('crawls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('start_url', sa.String(length=2048), nullable=False),
    sa.Column('max_urls', sa.Integer(), nullable=False),
    sa.Column('respect_robots_txt', sa.Boolean(), nullable=False),
    sa.Column('crawl_javascript', sa.Boolean(), nullable=False),
    sa.Column('follow_external_links', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='crawlstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('urls_crawled', sa.Integer(), nullable=False),
    sa.Column('urls_found', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('threshold_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('notify_dashboard', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'metric_name', 'threshold_type', name='uq_site_metric_type')
    )
    op.create_index('idx_alert_site_active', 'performance_alerts', ['site_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_performance_alerts_id'), 'performance_alerts', ['id'], unique=False)
    op.create_table('performance_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('competitor_url', sa.String(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('lcp', sa.Float(), nullable=True),
    sa.Column('fid', sa.Float(), nullable=True),
    sa.Column('cls', sa.Float(), nullable=True),
    sa.Column('inp', sa.Float(), nullable=True),
    sa.Column('ttfb', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('lcp_better', sa.Boolean(), nullable=True),
    sa.Column('fid_better', sa.Boolean(), nullable=True),
    sa.Column('cls_better', sa.Boolean(), nullable=True),
    sa.Column('inp_better', sa.Boolean(), nullable=True),
    sa.Column('overall_better', sa.Boolean(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'competitor_url', 'device_type', name='uq_site_competitor_device')
    )
    op.create_index('idx_benchmark_site_created', 'performance_benchmarks', ['site_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_performance_benchmarks_id'), 'performance_benchmarks', ['id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('lab_lcp', sa.Float(), nullable=True),
    sa.Column('lab_fid', sa.Float(), nullable=True),
    sa.Column('lab_cls', sa.Float(), nullable=True),
    sa.Column('lab_ttfb', sa.Float(), nullable=True),
    sa.Column('lab_fcp', sa.Float(), nullable=True),
    sa.Column('lab_si', sa.Float(), nullable=True),
    sa.Column('lab_tbt', sa.Float(), nullable=True),
    sa.Column('lab_tti', sa.Float(), nullable=True),
    sa.Column('field_lcp', sa.Float(), nullable=True),
    sa.Column('field_fid', sa.Float(), nullable=True),
    sa.Column('field_cls', sa.Float(), nullable=True),
    sa.Column('field_inp', sa.Float(), nullable=True),
    sa.Column('field_ttfb', sa.Float(), nullable=True),
    sa.Column('field_fcp', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('lcp_good', sa.Float(), nullable=True),
    sa.Column('lcp_needs_improvement', sa.Float(), nullable=True),
    sa.Column('lcp_poor', sa.Float(), nullable=True),
    sa.Column('fid_good', sa.Float(), nullable=True),
    sa.Column('fid_needs_improvement', sa.Float(), nullable=True),
    sa.Column('fid_poor', sa.Float(), nullable=True),
    sa.Column('cls_good', sa.Float(), nullable=True),
    sa.Column('cls_needs_improvement', sa.Float(), nullable=True),
    sa.Column('cls_poor', sa.Float(), nullable=True),
    sa.Column('inp_good', sa.Float(), nullable=True),
    sa.Column('inp_needs_improvement', sa.Float(), nullable=True),
    sa.Column('inp_poor', sa.Float(), nullable=True),
    sa.Column('crux_collection_period', sa.JSON(), nullable=True),
    sa.Column('lighthouse_version', sa.String(), nullable=True),
    sa.Column('raw_lighthouse_data', sa.JSON(), nullable=True),
    sa.Column('raw_crux_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_performance_site_created', 'performance_metrics', ['site_id', 'created_at'], unique=False)
    op.create_index('idx_performance_site_device', 'performance_metrics', ['site_id', 'device_type'], unique=False)
    op.create_index('idx_performance_url_created', 'performance_metrics', ['url', 'created_at'], unique=False)
    op.create_index(op.f('ix_performance_metrics_id'), 'performance_metrics', ['id'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pathway_type', sa.String(), nullable=True),
    sa.Column('estimated_success_probability', sa.Float(), nullable=True),
    sa.Column('estimated_timeframe_months', sa.Integer(), nullable=True),
    sa.Column('estimated_resource_cost', sa.String(), nullable=True),
    sa.Column('estimated_roi', sa.Float(), nullable=True),
    sa.Column('strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_id'), 'playbooks', ['id'], unique=False)
    op.create_index(op.f('ix_playbooks_playbook_id'), 'playbooks', ['playbook_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('ga4_property_id', sa.String(length=50), nullable=True),
    sa.Column('ga4_measurement_id', sa.String(length=50), nullable=True),
    sa.Column('ga4_configured', sa.Boolean(), nullable=False),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=False),
    sa.Column('profitability_tracking', sa.Boolean(), nullable=False),
    sa.Column('monthly_seo_budget', sa.Integer(), nullable=True),
    sa.Column('setup_status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_metric_name'), 'usage_records', ['metric_name'], unique=False)
    op.create_index(op.f('ix_usage_records_period_end'), 'usage_records', ['period_end'], unique=False)
    op.create_index(op.f('ix_usage_records_period_start'), 'usage_records', ['period_start'], unique=False)
    op.create_table('activity_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTER', 'USER_UPDATE', 'SITE_CREATED', 'SITE_UPDATED', 'SITE_DELETED', 'SITE_CRAWLED', 'PERFORMANCE_ANALYZED', 'PERFORMANCE_ALERT', 'PERFORMANCE_IMPROVED', 'PERFORMANCE_DEGRADED', 'SERP_ANALYZED', 'KEYWORD_RANKED', 'COMPETITOR_ADDED', 'BACKLINK_GAINED', 'CONTENT_CREATED', 'CONTENT_PUBLISHED', 'CONTENT_OPTIMIZED', 'MEMBER_INVITED', 'MEMBER_JOINED', 'MEMBER_LEFT', 'PERMISSION_CHANGED', 'SYSTEM_UPDATE', 'INTEGRATION_CONNECTED', 'INTEGRATION_DISCONNECTED', 'API_KEY_CREATED', name='activitytype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_avatar', sa.String(length=512), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_org_created', 'activity_feed', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_activity_project_created', 'activity_feed', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_activity_type_created', 'activity_feed', ['type', 'created_at'], unique=False)
    op.create_index('idx_activity_user_created', 'activity_feed', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_feed_id'), 'activity_feed', ['id'], unique=False)
    op.create_table('crawl_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('crawlability_score', sa.Integer(), nullable=False),
    sa.Column('indexable_pages', sa.Integer(), nullable=False),
    sa.Column('non_indexable_pages', sa.Integer(), nullable=False),
    sa.Column('crawl_depth_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_type_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_code_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_id')
    )
    op.create_table('crawl_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('crawl_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('url_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_extension', sa.String(length=50), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('storage_backend', sa.String(length=20), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('virus_scanned', sa.Boolean(), nullable=True),
    sa.Column('virus_scan_result', sa.String(length=50), nullable=True),
    sa.Column('virus_scan_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_checksum', 'files', ['checksum'], unique=False)
    op.create_index('idx_file_expires', 'files', ['expires_at'], unique=False)
    op.create_index('idx_file_org_category', 'files', ['organization_id', 'category'], unique=False)
    op.create_index('idx_file_project_status', 'files', ['project_id', 'status'], unique=False)
    op.create_index('idx_file_user_created', 'files', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_files_file_id'), 'files', ['file_id'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_organization_id'), 'files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'ALERT', 'SYSTEM', 'PERFORMANCE', 'SECURITY', 'BILLING', 'COLLABORATION', name='notificationtype'), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'PERFORMANCE', 'SEO', 'SECURITY', 'BILLING', 'TEAM', 'SYSTEM', 'ALERTS', name='notificationcategory'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('deliver_email', sa.Boolean(), nullable=False),
    sa.Column('deliver_push', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_expires', 'notifications', ['expires_at'], unique=False)
    op.create_index('idx_notification_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_notification_user_unread', 'notifications', ['user_id', 'is_read', 'is_archived'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('project_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_team_members_id'), 'project_team_members', ['id'], unique=False)
    op.create_table('social_media_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_token_secret', sa.Text(), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_access_created', 'file_access_logs', ['created_at'], unique=False)
    op.create_index('idx_file_access_file_user', 'file_access_logs', ['file_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_file_access_logs_file_id'), 'file_access_logs', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_access_logs_id'), 'file_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_file_access_logs_user_id'), 'file_access_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_access_logs_user_id'), table_name='file_access_logs')
    op.drop_index(op.f('ix_file_access_logs_id'), table_name='file_access_logs')
    op.drop_index(op.f('ix_file_access_logs_file_id'), table_name='file_access_logs')
    op.drop_index('idx_file_access_file_user', table_name='file_access_logs')
    op.drop_index('idx_file_access_created', table_name='file_access_logs')
    op.drop_table('file_access_logs')
    op.drop_table('webhooks')
    op.drop_table('social_media_credentials')
    op.drop_index(op.f('ix_project_team_members_id'), table_name='project_team_members')
    op.drop_table('project_team_members')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notification_user_unread', table_name='notifications')
    op.drop_index('idx_notification_user_created', table_name='notifications')
    op.drop_index('idx_notification_expires', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.drop_index(op.f('ix_files_organization_id'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_id'), table_name='files')
    op.drop_index('idx_file_user_created', table_name='files')
    op.drop_index('idx_file_project_status', table_name='files')
    op.drop_index('idx_file_org_category', table_name='files')
    op.drop_index('idx_file_expires', table_name='files')
    op.drop_index('idx_file_checksum', table_name='files')
    op.drop_table('files')
    op.drop_table('domain_verifications')
    op.drop_table('crawl_urls')
    op.drop_table('crawl_analyses')
    op.drop_index(op.f('ix_activity_feed_id'), table_name='activity_feed')
    op.drop_index('idx_activity_user_created', table_name='activity_feed')
    op.drop_index('idx_activity_type_created', table_name='activity_feed')
    op.drop_index('idx_activity_project_created', table_name='activity_feed')
    op.drop_index('idx_activity_org_created', table_name='activity_feed')
    op.drop_table('activity_feed')
    op.drop_index(op.f('ix_usage_records_period_start'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_period_end'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_metric_name'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_table('projects')
    op.drop_index(op.f('ix_playbooks_playbook_id'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_id'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index(op.f('ix_performance_metrics_id'), table_name='performance_metrics')
    op.drop_index('idx_performance_url_created', table_name='performance_metrics')
    op.drop_index('idx_performance_site_device', table_name='performance_metrics')
    op.drop_index('idx_performance_site_created', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_performance_benchmarks_id'), table_name='performance_benchmarks')
    op.drop_index('idx_benchmark_site_created', table_name='performance_benchmarks')
    op.drop_table('performance_benchmarks')
    op.drop_index(op.f('ix_performance_alerts_id'), table_name='performance_alerts')
    op.drop_index('idx_alert_site_active', table_name='performance_alerts')
    op.drop_table('performance_alerts')
    op.drop_table('crawls')
    op.drop_index(op.f('ix_billing_events_event_type'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index('idx_task_user_created', table_name='background_tasks')
    op.drop_index('idx_task_status_type', table_name='background_tasks')
    op.drop_index('idx_task_site_type', table_name='background_tasks')
    op.drop_index('idx_task_celery', table_name='background_tasks')
    op.drop_table('background_tasks')
    op.drop_index(op.f('ix_user_notification_preferences_id'), table_name='user_notification_preferences')
    op.drop_table('user_notification_preferences')
    op.drop_index(op.f('ix_usage_statistics_id'), table_name='usage_statistics')
    op.drop_table('usage_statistics')
    op.drop_index(op.f('ix_tuning_insights_insight_id'), table_name='tuning_insights')
    op.drop_index(op.f('ix_tuning_insights_id'), table_name='tuning_insights')
    op.drop_table('tuning_insights')
    op.drop_index(op.f('ix_threat_scenarios_threat_id'), table_name='threat_scenarios')
    op.drop_index(op.f('ix_threat_scenarios_id'), table_name='threat_scenarios')
    op.drop_table('threat_scenarios')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_email'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_strategic_ledger_strategy_id'), table_name='strategic_ledger')
    op.drop_index(op.f('ix_strategic_ledger_id'), table_name='strategic_ledger')
    op.drop_table('strategic_ledger')
    op.drop_table('sites')
    op.drop_index(op.f('ix_sge_monitors_monitor_id'), table_name='sge_monitors')
    op.drop_index(op.f('ix_sge_monitors_id'), table_name='sge_monitors')
    op.drop_table('sge_monitors')
    op.drop_index(op.f('ix_sge_analyses_id'), table_name='sge_analyses')
    op.drop_index(op.f('ix_sge_analyses_analysis_id'), table_name='sge_analyses')
    op.drop_table('sge_analyses')
    op.drop_index(op.f('ix_serp_feature_tracking_user_id'), table_name='serp_feature_tracking')
    op.drop_index(op.f('ix_serp_feature_tracking_query'), table_name='serp_feature_tracking')
    op.drop_index(op.f('ix_serp_feature_tracking_feature_name'), table_name='serp_feature_tracking')
    op.drop_table('serp_feature_tracking')
    op.drop_index(op.f('ix_serp_analyses_user_id'), table_name='serp_analyses')
    op.drop_index(op.f('ix_serp_analyses_query'), table_name='serp_analyses')
    op.drop_table('serp_analyses')
    op.drop_index(op.f('ix_scenarios_scenario_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_personalized_recommendations_recommendation_id'), table_name='personalized_recommendations')
    op.drop_index(op.f('ix_personalized_recommendations_id'), table_name='personalized_recommendations')
    op.drop_table('personalized_recommendations')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_organization_members_created_at'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_invitations_token'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_created_at'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_organization_domains_domain'), table_name='organization_domains')
    op.drop_index(op.f('ix_organization_domains_created_at'), table_name='organization_domains')
    op.drop_table('organization_domains')
    op.drop_index(op.f('ix_organization_audit_logs_created_at'), table_name='organization_audit_logs')
    op.drop_index(op.f('ix_organization_audit_logs_action'), table_name='organization_audit_logs')
    op.drop_table('organization_audit_logs')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_domains_full_domain'), table_name='domains')
    op.drop_index(op.f('ix_domains_domain'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_content_enhancements_id'), table_name='content_enhancements')
    op.drop_index(op.f('ix_content_enhancements_enhancement_id'), table_name='content_enhancements')
    op.drop_table('content_enhancements')
    op.drop_index(op.f('ix_content_briefs_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_brief_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_index(op.f('ix_competitor_tracking_user_id'), table_name='competitor_tracking')
    op.drop_index(op.f('ix_competitor_tracking_domain'), table_name='competitor_tracking')
    op.drop_table('competitor_tracking')
    op.drop_index(op.f('ix_competitive_intelligence_intelligence_id'), table_name='competitive_intelligence')
    op.drop_index(op.f('ix_competitive_intelligence_id'), table_name='competitive_intelligence')
    op.drop_table('competitive_intelligence')
    op.drop_index(op.f('ix_captured_knowledge_knowledge_id'), table_name='captured_knowledge')
    op.drop_index(op.f('ix_captured_knowledge_id'), table_name='captured_knowledge')
    op.drop_table('captured_knowledge')
    op.drop_index('idx_audit_logs_user_id_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource_type_resource_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_activity_summaries_id'), table_name='activity_summaries')
    op.drop_index('idx_summary_org_date', table_name='activity_summaries')
    op.drop_table('activity_summaries')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###