"""invitations and project verification token

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 17:56:18.942282+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import helpers
revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('role', postgresql.ENUM(name='member_role', create_type=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_invitations_invited_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invitations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash'))
    )
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.add_column('projects', sa.Column('verification_token', sa.String(length=64), nullable=True))
    op.drop_column('projects', 'verification_token_hash')
    # ### end Alembic commands ###
    helpers.enable_tenant_rls("invitations")
    helpers.execute_all(
        # Accepting an invitation happens before the tenant is bound (the user is not a
        # member yet): look up exactly one invitation by its token hash.
        """CREATE FUNCTION app_lookup_invitation(p_token_hash text)
          RETURNS TABLE (id uuid, organization_id uuid, email text, role text,
                         expires_at timestamptz, accepted_at timestamptz,
                         revoked_at timestamptz)
          LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp
          AS $$
            SELECT id, organization_id, email::text, role::text, expires_at, accepted_at,
                   revoked_at
              FROM invitations WHERE token_hash = p_token_hash
          $$""",
        "REVOKE ALL ON FUNCTION app_lookup_invitation(text) FROM PUBLIC",
        f"GRANT EXECUTE ON FUNCTION app_lookup_invitation(text) TO {helpers.APP_ROLE}",
    )


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS app_lookup_invitation(text)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('verification_token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('projects', 'verification_token')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
