"""onpage briefs llm usage

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-24 19:59:56.991120+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import helpers
from sqlalchemy.dialects import postgresql
revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_llm_usage_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('month', 'organization_id', 'purpose', name=op.f('pk_llm_usage'))
    )
    op.create_table('content_briefs',
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'cancelled', name='analysis_status'), nullable=False),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_content_briefs_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_id'], ['project_markets.id'], name=op.f('fk_content_briefs_market_id_project_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_content_briefs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_content_briefs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_briefs'))
    )
    op.create_index(op.f('ix_content_briefs_organization_id'), 'content_briefs', ['organization_id'], unique=False)
    op.create_index('ix_content_briefs_project', 'content_briefs', ['project_id', 'created_at'], unique=False)
    op.create_table('page_optimizations',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rewrite', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'cancelled', name='analysis_status'), nullable=False),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_page_optimizations_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_id'], ['project_markets.id'], name=op.f('fk_page_optimizations_market_id_project_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_page_optimizations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_page_optimizations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_optimizations'))
    )
    op.create_index(op.f('ix_page_optimizations_organization_id'), 'page_optimizations', ['organization_id'], unique=False)
    op.create_index('ix_page_optimizations_project', 'page_optimizations', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    for table in ("llm_usage", "content_briefs", "page_optimizations"):
        helpers.enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_optimizations_project', table_name='page_optimizations')
    op.drop_index(op.f('ix_page_optimizations_organization_id'), table_name='page_optimizations')
    op.drop_table('page_optimizations')
    op.drop_index('ix_content_briefs_project', table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_organization_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
    sa.Enum(name="analysis_status").drop(op.get_bind(), checkfirst=True)
