"""search data keywords rankings

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 19:40:25.853422+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import helpers
from sqlalchemy.dialects import postgresql
revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_metrics',
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('language', sa.String(length=35), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('avg_monthly_searches', sa.Integer(), nullable=True),
    sa.Column('volume_is_range', sa.Boolean(), nullable=False),
    sa.Column('competition', sa.String(length=20), nullable=True),
    sa.Column('cpc_low_micros', sa.BigInteger(), nullable=True),
    sa.Column('cpc_high_micros', sa.BigInteger(), nullable=True),
    sa.Column('monthly', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_on', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_metrics')),
    sa.UniqueConstraint('keyword', 'country', 'language', 'source', name=op.f('uq_keyword_metrics_keyword_country_language_source'))
    )
    op.create_table('serp_snapshots',
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('language', sa.String(length=35), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('device', sa.String(length=10), nullable=False),
    sa.Column('fetched_on', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vendor', sa.String(length=30), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_snapshots'))
    )
    op.create_index('uq_serp_snapshots_key', 'serp_snapshots', ['engine', 'query', 'country', 'language', sa.literal_column("coalesce(location, '')"), 'device', 'fetched_on'], unique=True)
    op.create_table('serp_validations',
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('primary_vendor', sa.String(length=30), nullable=False),
    sa.Column('secondary_vendor', sa.String(length=30), nullable=False),
    sa.Column('top10_overlap', sa.Float(), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_validations'))
    )
    op.create_table('vendor_usage',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=30), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('day', 'vendor', 'engine', name=op.f('pk_vendor_usage'))
    )
    op.create_table('rank_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('is_own', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('ai_cited', sa.Boolean(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rank_observations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk_rank_observations'))
    )
    op.create_index('ix_rank_obs_keyword_date', 'rank_observations', ['keyword_id', 'date'], unique=False)
    op.create_index(op.f('ix_rank_observations_organization_id'), 'rank_observations', ['organization_id'], unique=False)
    op.create_table('serp_usage',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_serp_usage_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day', 'organization_id', name=op.f('pk_serp_usage'))
    )
    op.create_table('competitors',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competitors_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_competitors_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors')),
    sa.UniqueConstraint('project_id', 'domain', name=op.f('uq_competitors_project_id_domain'))
    )
    op.create_index(op.f('ix_competitors_organization_id'), 'competitors', ['organization_id'], unique=False)
    op.create_table('tracked_keywords',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['project_markets.id'], name=op.f('fk_tracked_keywords_market_id_project_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tracked_keywords_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tracked_keywords_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracked_keywords')),
    sa.UniqueConstraint('market_id', 'keyword', name=op.f('uq_tracked_keywords_market_id_keyword'))
    )
    op.create_index(op.f('ix_tracked_keywords_organization_id'), 'tracked_keywords', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tracked_keywords_project_id'), 'tracked_keywords', ['project_id'], unique=False)
    # ### end Alembic commands ###
    helpers.create_hypertable("rank_observations", "date", "30 days")
    # Global public data (no tenant column): readable and writable by the app role;
    # nothing in these tables identifies an organization.
    for table in ("serp_snapshots", "keyword_metrics", "vendor_usage", "serp_validations"):
        helpers.grant_table(table, "SELECT, INSERT, UPDATE")
    for table in ("tracked_keywords", "competitors", "rank_observations", "serp_usage"):
        helpers.enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_keywords_project_id'), table_name='tracked_keywords')
    op.drop_index(op.f('ix_tracked_keywords_organization_id'), table_name='tracked_keywords')
    op.drop_table('tracked_keywords')
    op.drop_index(op.f('ix_competitors_organization_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_table('serp_usage')
    op.drop_index(op.f('ix_rank_observations_organization_id'), table_name='rank_observations')
    op.drop_index('ix_rank_obs_keyword_date', table_name='rank_observations')
    op.drop_table('rank_observations')
    op.drop_table('vendor_usage')
    op.drop_table('serp_validations')
    op.drop_index('uq_serp_snapshots_key', table_name='serp_snapshots')
    op.drop_table('serp_snapshots')
    op.drop_table('keyword_metrics')
    # ### end Alembic commands ###
