"""baseline tenancy schema

Users, organizations, memberships, projects, target markets and the audit log, with
Row-Level Security (docs/execution-plan.md §5.2) and explicit per-table grants.

Revision ID: 0001
Revises:
Create Date: 2026-09-24 17:16:55.637514+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import helpers

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    helpers.require_roles()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("google_subject", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_platform_staff", sa.Boolean(), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_subject", name=op.f("uq_users_google_subject")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("plan_code", sa.String(length=40), nullable=False),
        sa.Column("require_mfa", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_organizations_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "editor", "viewer", "billing", name="member_role"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_memberships_organization_id_user_id")
        ),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("primary_domain", postgresql.CITEXT(), nullable=False),
        sa.Column("domain_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_method", sa.String(length=20), nullable=True),
        sa.Column("verification_token_hash", sa.String(length=64), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_projects_org_domain_active",
        "projects",
        ["organization_id", "primary_domain"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "project_markets",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("language", sa.String(length=35), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("device", sa.Enum("desktop", "mobile", name="device"), nullable=False),
        sa.Column(
            "search_engines",
            postgresql.ARRAY(
                sa.Enum(
                    "google",
                    "bing",
                    "yahoo",
                    "duckduckgo",
                    "yandex",
                    "baidu",
                    "naver",
                    "seznam",
                    name="search_engine",
                )
            ),
            nullable=False,
        ),
        sa.Column(
            "ai_engines",
            postgresql.ARRAY(
                sa.Enum(
                    "google_ai_overview",
                    "google_ai_mode",
                    "chatgpt",
                    "perplexity",
                    "gemini",
                    "copilot",
                    "claude",
                    name="ai_engine",
                )
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("country ~ '^[A-Z]{2}$'", name=op.f("ck_project_markets_country_iso2")),
        sa.CheckConstraint(
            "cardinality(search_engines) >= 1", name=op.f("ck_project_markets_has_engine")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_project_markets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_markets_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_markets")),
    )
    op.create_index(
        op.f("ix_project_markets_organization_id"),
        "project_markets",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_markets_project_id"), "project_markets", ["project_id"], unique=False
    )
    op.create_index(
        "uq_project_markets_target",
        "project_markets",
        [
            "project_id",
            "country",
            "language",
            sa.literal_column("coalesce(location, '')"),
            "device",
        ],
        unique=True,
    )
    # ### end Alembic commands ###
    _security()


def _security() -> None:
    helpers.create_identity_functions()

    # users: global accounts, accessed only through the identity module (login must look
    # users up by email before any identity is bound). No RLS; the app role may not
    # delete users (account deletion runs as a system job with a grace period).
    helpers.grant_table("users", "SELECT, INSERT, UPDATE")

    # organizations: visible when bound as tenant or when the acting user is a member.
    helpers.grant_table("organizations")
    helpers.enable_rls_only("organizations")
    helpers.execute_all(
        """CREATE POLICY org_select ON organizations FOR SELECT USING (
          id = app_current_org_id()
          OR EXISTS (SELECT 1 FROM memberships m
                     WHERE m.organization_id = organizations.id
                       AND m.user_id = app_current_user_id()))""",
        """CREATE POLICY org_insert ON organizations FOR INSERT
          WITH CHECK (created_by_user_id = app_current_user_id())""",
        """CREATE POLICY org_update ON organizations FOR UPDATE
          USING (id = app_current_org_id()) WITH CHECK (id = app_current_org_id())""",
        """CREATE POLICY org_delete ON organizations FOR DELETE
          USING (id = app_current_org_id())""",
    )

    # memberships: tenant rows, plus a user's own memberships across organizations
    # (needed to list "my organizations" before a tenant is chosen).
    helpers.grant_table("memberships")
    helpers.enable_rls_only("memberships")
    helpers.execute_all(
        """CREATE POLICY membership_select ON memberships FOR SELECT USING (
          organization_id = app_current_org_id() OR user_id = app_current_user_id())""",
        """CREATE POLICY membership_write ON memberships FOR ALL
          USING (organization_id = app_current_org_id())
          WITH CHECK (organization_id = app_current_org_id())""",
    )

    helpers.enable_tenant_rls("projects")
    helpers.enable_tenant_rls("project_markets")

    # audit_events: append-only for the app role (no UPDATE/DELETE grant at all).
    helpers.grant_table("audit_events", "SELECT, INSERT")
    helpers.enable_rls_only("audit_events")
    helpers.execute_all(
        """CREATE POLICY audit_select ON audit_events FOR SELECT USING (
          organization_id = app_current_org_id()
          OR (organization_id IS NULL AND actor_user_id = app_current_user_id()))""",
        """CREATE POLICY audit_insert ON audit_events FOR INSERT WITH CHECK (
          organization_id IS NULL OR organization_id = app_current_org_id())""",
    )


def downgrade() -> None:
    # The organizations SELECT policy references memberships; drop it before the tables.
    op.execute("DROP POLICY IF EXISTS org_select ON organizations")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_project_markets_target", table_name="project_markets")
    op.drop_index(op.f("ix_project_markets_project_id"), table_name="project_markets")
    op.drop_index(op.f("ix_project_markets_organization_id"), table_name="project_markets")
    op.drop_table("project_markets")
    op.drop_index(
        "uq_projects_org_domain_active",
        table_name="projects",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("organizations")
    op.drop_table("users")
    # ### end Alembic commands ###
    for enum_name in ("ai_engine", "search_engine", "device", "member_role"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    op.execute("DROP FUNCTION IF EXISTS app_current_org_id(), app_current_user_id()")
