"""integrations and indexing

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-24 19:13:14.156883+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import helpers

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_performance_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('surface', sa.String(length=40), nullable=False),
    sa.Column('page', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_performance_daily_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk_ai_performance_daily'))
    )
    op.create_index('ix_ai_perf_project_date', 'ai_performance_daily', ['project_id', 'source', 'date'], unique=False)
    op.create_index(op.f('ix_ai_performance_daily_organization_id'), 'ai_performance_daily', ['organization_id'], unique=False)
    op.create_table('bing_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_bing_daily_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk_bing_daily'))
    )
    op.create_index(op.f('ix_bing_daily_organization_id'), 'bing_daily', ['organization_id'], unique=False)
    op.create_index('ix_bing_daily_project_date', 'bing_daily', ['project_id', 'date'], unique=False)
    op.create_table('connections',
    sa.Column('provider', sa.Enum('google', 'bing', name='integration_provider'), nullable=False),
    sa.Column('status', sa.Enum('active', 'error', 'reauth_required', name='connection_status'), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('account_label', sa.String(length=320), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], name=op.f('fk_connections_connected_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_connections_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections')),
    sa.UniqueConstraint('organization_id', 'provider', name=op.f('uq_connections_organization_id_provider'))
    )
    op.create_index(op.f('ix_connections_organization_id'), 'connections', ['organization_id'], unique=False)
    op.create_table('ga4_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('landing_page', sa.Text(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('engaged_sessions', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ga4_daily_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk_ga4_daily'))
    )
    op.create_index(op.f('ix_ga4_daily_organization_id'), 'ga4_daily', ['organization_id'], unique=False)
    op.create_index('ix_ga4_daily_project_date', 'ga4_daily', ['project_id', 'date'], unique=False)
    op.create_table('gsc_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('page', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('device', sa.String(length=10), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_gsc_daily_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk_gsc_daily'))
    )
    op.create_index(op.f('ix_gsc_daily_organization_id'), 'gsc_daily', ['organization_id'], unique=False)
    op.create_index('ix_gsc_daily_project_date', 'gsc_daily', ['project_id', 'date'], unique=False)
    op.create_table('vitals_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('form_factor', sa.String(length=10), nullable=False),
    sa.Column('lcp_ms', sa.Float(), nullable=True),
    sa.Column('inp_ms', sa.Float(), nullable=True),
    sa.Column('cls', sa.Float(), nullable=True),
    sa.Column('fcp_ms', sa.Float(), nullable=True),
    sa.Column('ttfb_ms', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_vitals_daily_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk_vitals_daily'))
    )
    op.create_index(op.f('ix_vitals_daily_organization_id'), 'vitals_daily', ['organization_id'], unique=False)
    op.create_index('ix_vitals_project_date', 'vitals_daily', ['project_id', 'date'], unique=False)
    op.create_table('indexing_submissions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url_count', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('urls', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_indexing_submissions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_indexing_submissions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indexing_submissions'))
    )
    op.create_index(op.f('ix_indexing_submissions_organization_id'), 'indexing_submissions', ['organization_id'], unique=False)
    op.create_index('ix_indexing_submissions_project', 'indexing_submissions', ['project_id', 'submitted_at'], unique=False)
    op.create_table('project_sources',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('gsc', 'ga4', 'bing', 'indexnow', name='source_kind'), nullable=False),
    sa.Column('property_id', sa.String(length=500), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=40), nullable=True),
    sa.Column('synced_through', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_project_sources_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_sources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_sources')),
    sa.UniqueConstraint('project_id', 'kind', name=op.f('uq_project_sources_project_id_kind'))
    )
    op.create_index(op.f('ix_project_sources_organization_id'), 'project_sources', ['organization_id'], unique=False)
    op.create_table('url_inspections',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verdict', sa.String(length=40), nullable=True),
    sa.Column('coverage_state', sa.String(length=200), nullable=True),
    sa.Column('indexing_state', sa.String(length=80), nullable=True),
    sa.Column('robots_state', sa.String(length=80), nullable=True),
    sa.Column('page_fetch_state', sa.String(length=80), nullable=True),
    sa.Column('last_crawl_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_canonical', sa.Text(), nullable=True),
    sa.Column('user_canonical', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_url_inspections_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_url_inspections_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_url_inspections'))
    )
    op.create_index(op.f('ix_url_inspections_organization_id'), 'url_inspections', ['organization_id'], unique=False)
    op.create_index('ix_url_inspections_project_url', 'url_inspections', ['project_id', 'url'], unique=False)
    # ### end Alembic commands ###
    # Daily metrics are time-series: TimescaleDB hypertables, 30-day chunks.
    for table in ("gsc_daily", "ga4_daily", "bing_daily", "ai_performance_daily", "vitals_daily"):
        helpers.create_hypertable(table, "date", "30 days")
    for table in (
        "connections",
        "project_sources",
        "url_inspections",
        "indexing_submissions",
        "gsc_daily",
        "ga4_daily",
        "bing_daily",
        "ai_performance_daily",
        "vitals_daily",
    ):
        helpers.enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_inspections_project_url', table_name='url_inspections')
    op.drop_index(op.f('ix_url_inspections_organization_id'), table_name='url_inspections')
    op.drop_table('url_inspections')
    op.drop_index(op.f('ix_project_sources_organization_id'), table_name='project_sources')
    op.drop_table('project_sources')
    op.drop_index('ix_indexing_submissions_project', table_name='indexing_submissions')
    op.drop_index(op.f('ix_indexing_submissions_organization_id'), table_name='indexing_submissions')
    op.drop_table('indexing_submissions')
    op.drop_index('ix_vitals_project_date', table_name='vitals_daily')
    op.drop_index(op.f('ix_vitals_daily_organization_id'), table_name='vitals_daily')
    op.drop_table('vitals_daily')
    op.drop_index('ix_gsc_daily_project_date', table_name='gsc_daily')
    op.drop_index(op.f('ix_gsc_daily_organization_id'), table_name='gsc_daily')
    op.drop_table('gsc_daily')
    op.drop_index('ix_ga4_daily_project_date', table_name='ga4_daily')
    op.drop_index(op.f('ix_ga4_daily_organization_id'), table_name='ga4_daily')
    op.drop_table('ga4_daily')
    op.drop_index(op.f('ix_connections_organization_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index('ix_bing_daily_project_date', table_name='bing_daily')
    op.drop_index(op.f('ix_bing_daily_organization_id'), table_name='bing_daily')
    op.drop_table('bing_daily')
    op.drop_index(op.f('ix_ai_performance_daily_organization_id'), table_name='ai_performance_daily')
    op.drop_index('ix_ai_perf_project_date', table_name='ai_performance_daily')
    op.drop_table('ai_performance_daily')
    # ### end Alembic commands ###
    for enum in ("integration_provider", "connection_status", "source_kind"):
        op.execute(f"DROP TYPE IF EXISTS {enum}")
