"""billing

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-25 00:00:26.878819+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import helpers
from sqlalchemy.dialects import postgresql
revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('org_ref', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_events'))
    )
    op.create_table('organization_billing',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=80), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('plan_code', sa.String(length=40), nullable=False),
    sa.Column('addons', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_billing_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_organization_billing')),
    sa.UniqueConstraint('stripe_customer_id', name=op.f('uq_organization_billing_stripe_customer_id'))
    )
    op.add_column('organizations', sa.Column('addons', postgresql.ARRAY(sa.String(length=40)), server_default='{}', nullable=False))
    # ### end Alembic commands ###
    helpers.enable_tenant_rls("organization_billing")
    # Global replay guard for webhooks (no tenant data).
    helpers.grant_table("stripe_events", "SELECT, INSERT")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'addons')
    op.drop_table('organization_billing')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
