"""jobs crawls and audit issues

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 18:39:02.327224+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import helpers

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('counters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_jobs_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_org_created', 'jobs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index('uq_jobs_active_per_project', 'jobs', ['project_id', 'kind'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running') AND project_id IS NOT NULL"))
    op.create_table('crawls',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'cancelled', name='crawl_status'), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('domain_verified', sa.Boolean(), nullable=False),
    sa.Column('engines', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('budget_exhausted', sa.Boolean(), nullable=False),
    sa.Column('render_available', sa.Boolean(), nullable=False),
    sa.Column('site', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('issue_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_crawls_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_crawls_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_crawls_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawls'))
    )
    op.create_index(op.f('ix_crawls_organization_id'), 'crawls', ['organization_id'], unique=False)
    op.create_index('ix_crawls_project_created', 'crawls', ['project_id', 'created_at'], unique=False)
    op.create_table('audit_issues',
    sa.Column('crawl_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='issue_severity'), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], name=op.f('fk_audit_issues_crawl_id_crawls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_issues_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_issues'))
    )
    op.create_index('ix_audit_issues_crawl_rule', 'audit_issues', ['crawl_id', 'rule_id'], unique=False)
    op.create_index(op.f('ix_audit_issues_organization_id'), 'audit_issues', ['organization_id'], unique=False)
    op.create_table('crawl_pages',
    sa.Column('crawl_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('found_via', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=40), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('redirect_to', sa.Text(), nullable=True),
    sa.Column('in_sitemap', sa.Boolean(), nullable=False),
    sa.Column('allowed_google', sa.Boolean(), nullable=False),
    sa.Column('allowed_bing', sa.Boolean(), nullable=False),
    sa.Column('indexable_google', sa.Boolean(), nullable=False),
    sa.Column('indexable_bing', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('canonical', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('simhash', sa.BigInteger(), nullable=True),
    sa.Column('inlinks', sa.Integer(), nullable=False),
    sa.Column('x_robots', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rendered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mobile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], name=op.f('fk_crawl_pages_crawl_id_crawls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_crawl_pages_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_pages')),
    sa.UniqueConstraint('crawl_id', 'url', name=op.f('uq_crawl_pages_crawl_id_url'))
    )
    op.create_index(op.f('ix_crawl_pages_crawl_id'), 'crawl_pages', ['crawl_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_organization_id'), 'crawl_pages', ['organization_id'], unique=False)
    op.create_table('crawl_links',
    sa.Column('crawl_id', sa.UUID(), nullable=False),
    sa.Column('source_page_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('nofollow', sa.Boolean(), nullable=False),
    sa.Column('anchor', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], name=op.f('fk_crawl_links_crawl_id_crawls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_crawl_links_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_page_id'], ['crawl_pages.id'], name=op.f('fk_crawl_links_source_page_id_crawl_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_links'))
    )
    op.create_index(op.f('ix_crawl_links_organization_id'), 'crawl_links', ['organization_id'], unique=False)
    op.create_index('ix_crawl_links_target', 'crawl_links', ['crawl_id', 'target_url'], unique=False)
    op.add_column('projects', sa.Column('crawl_schedule', sa.String(length=10), server_default='off', nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_projects_crawl_schedule"),
        "projects",
        "crawl_schedule IN ('off', 'weekly', 'monthly')",
    )
    for table in ("jobs", "crawls", "crawl_pages", "crawl_links", "audit_issues"):
        helpers.enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_projects_crawl_schedule"), "projects", type_="check")
    op.drop_column('projects', 'crawl_schedule')
    op.drop_index('ix_crawl_links_target', table_name='crawl_links')
    op.drop_index(op.f('ix_crawl_links_organization_id'), table_name='crawl_links')
    op.drop_table('crawl_links')
    op.drop_index(op.f('ix_crawl_pages_organization_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_crawl_id'), table_name='crawl_pages')
    op.drop_table('crawl_pages')
    op.drop_index(op.f('ix_audit_issues_organization_id'), table_name='audit_issues')
    op.drop_index('ix_audit_issues_crawl_rule', table_name='audit_issues')
    op.drop_table('audit_issues')
    op.drop_index('ix_crawls_project_created', table_name='crawls')
    op.drop_index(op.f('ix_crawls_organization_id'), table_name='crawls')
    op.drop_table('crawls')
    op.drop_index('uq_jobs_active_per_project', table_name='jobs', postgresql_where=sa.text("status IN ('queued', 'running') AND project_id IS NOT NULL"))
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index('ix_jobs_org_created', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
    for enum in ("job_status", "crawl_status", "issue_severity"):
        op.execute(f"DROP TYPE IF EXISTS {enum}")
