"""identity mfa passkeys tokens api keys

User-owned identity tables are protected by RLS on ``app_current_user_id()``. A few
lookups must happen *before* an identity is bound (redeeming an emailed token,
authenticating an API key or a passkey). They go through narrowly scoped
``SECURITY DEFINER`` functions that return only what the caller needs for one exact
key, instead of giving the application role broad read access.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 17:22:07.478230+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import helpers
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_tokens_token_hash'))
    )
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_table('mfa_totp',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_step', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mfa_totp_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_mfa_totp'))
    )
    op.create_table('recovery_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_codes'))
    )
    op.create_index(op.f('ix_recovery_codes_user_id'), 'recovery_codes', ['user_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.BigInteger(), nullable=False),
    sa.Column('transports', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('backed_up', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_webauthn_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webauthn_credentials')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_webauthn_credentials_credential_id'))
    )
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_api_keys_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_api_keys_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('prefix', name=op.f('uq_api_keys_prefix'))
    )
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    # ### end Alembic commands ###
    _security()


_USER_OWNED = ("mfa_totp", "recovery_codes", "webauthn_credentials", "email_tokens")


def _security() -> None:
    for table in _USER_OWNED:
        helpers.grant_table(table)
        helpers.enable_rls_only(table)
        op.execute(
            f"CREATE POLICY user_isolation ON {table} "
            f"USING (user_id = app_current_user_id()) "
            f"WITH CHECK (user_id = app_current_user_id())"
        )
    helpers.enable_tenant_rls("api_keys")

    helpers.execute_all(
        # Redeem an email token atomically: single use, unexpired, purpose-bound.
        """CREATE FUNCTION app_consume_email_token(p_token_hash text, p_purpose text)
          RETURNS uuid LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp
          AS $$
            UPDATE email_tokens SET used_at = now()
             WHERE token_hash = p_token_hash AND purpose = p_purpose
               AND used_at IS NULL AND expires_at > now()
            RETURNING user_id
          $$""",
        # Authenticate an API key by its public prefix (secret hash compared in Python).
        """CREATE FUNCTION app_lookup_api_key(p_prefix text)
          RETURNS TABLE (id uuid, organization_id uuid, secret_hash text, scopes text[],
                         expires_at timestamptz, revoked_at timestamptz)
          LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp
          AS $$
            SELECT id, organization_id, secret_hash, scopes::text[], expires_at, revoked_at
              FROM api_keys WHERE prefix = p_prefix
          $$""",
        # Find which user owns a passkey during passwordless sign-in.
        """CREATE FUNCTION app_lookup_webauthn_user(p_credential_id bytea)
          RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp
          AS $$ SELECT user_id FROM webauthn_credentials WHERE credential_id = p_credential_id $$""",
        "REVOKE ALL ON FUNCTION app_consume_email_token(text, text) FROM PUBLIC",
        "REVOKE ALL ON FUNCTION app_lookup_api_key(text) FROM PUBLIC",
        "REVOKE ALL ON FUNCTION app_lookup_webauthn_user(bytea) FROM PUBLIC",
        f"GRANT EXECUTE ON FUNCTION app_consume_email_token(text, text), "
        f"app_lookup_api_key(text), app_lookup_webauthn_user(bytea) TO {helpers.APP_ROLE}",
    )


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS app_consume_email_token(text, text)")
    op.execute("DROP FUNCTION IF EXISTS app_lookup_api_key(text)")
    op.execute("DROP FUNCTION IF EXISTS app_lookup_webauthn_user(bytea)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_recovery_codes_user_id'), table_name='recovery_codes')
    op.drop_table('recovery_codes')
    op.drop_table('mfa_totp')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_table('email_tokens')
    # ### end Alembic commands ###
