"""ai visibility

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 20:17:27.185762+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import helpers
from sqlalchemy.dialects import postgresql
revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.String(length=30), nullable=False),
    sa.Column('sample', sa.Integer(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('mentioned', sa.Boolean(), nullable=False),
    sa.Column('cited', sa.Boolean(), nullable=False),
    sa.Column('mention_rank', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_observations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk_ai_observations'))
    )
    op.create_index('ix_ai_obs_project_date', 'ai_observations', ['project_id', 'date'], unique=False)
    op.create_index(op.f('ix_ai_observations_organization_id'), 'ai_observations', ['organization_id'], unique=False)
    op.create_table('ai_profiles',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('brand_terms', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('samples_per_prompt', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_profiles_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_ai_profiles'))
    )
    op.create_index(op.f('ix_ai_profiles_organization_id'), 'ai_profiles', ['organization_id'], unique=False)
    op.create_table('ai_prompts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.String(length=500), nullable=False),
    sa.Column('keyword', sa.String(length=300), nullable=True),
    sa.Column('engines', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['project_markets.id'], name=op.f('fk_ai_prompts_market_id_project_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_prompts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_prompts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_prompts'))
    )
    op.create_index(op.f('ix_ai_prompts_organization_id'), 'ai_prompts', ['organization_id'], unique=False)
    op.create_index('ix_ai_prompts_project', 'ai_prompts', ['project_id'], unique=False)
    # ### end Alembic commands ###
    helpers.create_hypertable("ai_observations", "date", "30 days")
    for table in ("ai_profiles", "ai_prompts", "ai_observations"):
        helpers.enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_prompts_project', table_name='ai_prompts')
    op.drop_index(op.f('ix_ai_prompts_organization_id'), table_name='ai_prompts')
    op.drop_table('ai_prompts')
    op.drop_index(op.f('ix_ai_profiles_organization_id'), table_name='ai_profiles')
    op.drop_table('ai_profiles')
    op.drop_index(op.f('ix_ai_observations_organization_id'), table_name='ai_observations')
    op.drop_index('ix_ai_obs_project_date', table_name='ai_observations')
    op.drop_table('ai_observations')
    # ### end Alembic commands ###
